### ISSUE TITLE
instructions without composer

### ISSUE THREAD

**Issue by MissAnna123** [o/sitemap-php#27]
Hi,
Can we have the instruction for installation and use without composer ?

for exemple : without composer, we don"t have : "use XMLWriter;".
Thanks for,
Best regards.

**Comment by evert** [comment]
Composer is required. And PHP namespaces are not in any way related to composer `use x` is part of PHP since version 5.4.

**Comment by MissAnna123** [comment]
Hi,

I asked you the question, beaucoup some product give the solution 
without composer :

for exemple this product  I use : 
https://github.com/matthiasmullie/minify/issues/83


I have no composer on the website I developped :-(

I use your product since few years... and I don't find other product to 
generat sitemap :-(


Do you know on other product without composer ?


Thanks for.



Le 21/11/2017 à 16:45, Evert Pot a écrit :

**Comment by evert** [comment]
I misspoke, I thought this was a question for a project I manage but it;s not, so I quickly deleted my comment afterwards. Really sorry about that.I can't speak for this project, but I would strongly suggest you upgrade your development environment and start learning composer

**Comment by MissAnna123** [comment]
arf, sorry,

I only use small computer hosting where I don't have the hand on the 
server. That's why I don't have composer :-(

I used yor sitemap production, the version of 2015.. aber I can not 
update your product on my developped website, because I can not update 
my developement environment, that's only small hosting.

Thanks for your answer... Your product version 2015 is running on 
PHP7.1...  I did the migration php 5.6 to php7.


Best regards.


Le 21/11/2017 à 16:56, Evert Pot a écrit :

**Comment by o** [comment]
Hi @MissAnna123, 

I am also planning to upgrade this library to use with composer and PHP7. And the master version of library is not complete. I would also suggest to upgrade your environment and start using composer like @evert (Hi man, hello from cloudy A'dam)

So you can still use the old version
https://github.com/o/sitemap-php/tree/36cc358e3914e78d4e1b332ec535991c3f3f4885
And you can download from here as zip. https://github.com/o/sitemap-php/archive/36cc358e3914e78d4e1b332ec535991c3f3f4885.zip

O.

**Comment by MissAnna123** [comment]
thanks.
I know that I will need to change hosting if I want to use ssh and composer :-(.
best regards,
thanks for answer.

**Comment by evert** [comment]
@MissAnna123 composer is just a small php tool. Anything that supports PHP will support composer just fine.

**Comment by MissAnna123** [comment]
Sure... I have two different hosting... any of them let me having a console ... snif
I search a solution :-(.. I don't know how for the moment.
I manage volunteer website actually without console.. with old hosting.. no console on server.. then I actually don't find solution how to install composer using command line !

**Comment by MissAnna123** [comment]
Hi, theres a probleme with the installation with composer 👍 
https://packagist.org/packages/osm/sitemap-php


xxxxxxxxxxxxxxxx\composer>composer require osm/sitemap-php


  [InvalidArgumentException]
  Could not find package osm/sitemap-php at any version for your minimum-stab
  ility (stable). Check the package spelling or your minimum-stability


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest]
 [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--
ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|
--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<
packages>]...

**Comment by o** [comment]
Hi please use fork of @evert temporarily. This repository still not stable. Thanks

composer require evert/sitemap-php

**Comment by mort3za** [comment]
@MissAnna123 I had the same issue. You can run this command: `composer require "osm/sitemap-php @dev"`  
But it's better that maintainer of this repo generate a release in github to fix this problem.

**Comment by claireliao0619** [comment]
@o Osman Ungur

Be honest, I feel so hurtful 😔😢 and sorrowful 😿every single moment when I think of you abusing my trust to do you blowjob came all way and masturbation* and then in the end, you didn't keep your promise(you promised I could stay until next Wed, you promised you'll come to Frankfurt, you promised I can also ask for Skype Masturbation whenever I need)

![IMG_fzs812](https://user-images.githubusercontent.com/55841755/65698174-6a918900-e07c-11e9-976f-b3fa6796e549.jpg)
![IMG_-b9mpd7](https://user-images.githubusercontent.com/55841755/65698203-75e4b480-e07c-11e9-8a4e-9bc2d46fc8ab.jpg)
![IMG_yoqo8p](https://user-images.githubusercontent.com/55841755/65698240-7d0bc280-e07c-11e9-8c99-b31c2872dbf9.jpg)
![IMG_-60ly5b](https://user-images.githubusercontent.com/55841755/65698272-8a28b180-e07c-11e9-9acc-581d880099b1.jpg)
![IMG_-ud3t01](https://user-images.githubusercontent.com/558
![IMG_7q3b87](https://user-images.githubusercontent.com/55841755/65698383-b5130580-e07c-11e9-9dea-c06569e12f23.jpg)
41755/65698340-a4fb2600-e07c-11e9-89e9-62fc6a8f8798.jpg)




but, you didn't keep your promise(you promised I could stay until next Wed, you promised you'll come to Frankfurt, you promised I can also ask for Skype Masturbation if I need)
![Screenshot_20190926-081828](https://user-images.githubusercontent.com/55841755/65697927-0cfd3c80-e07c-11e9-84c6-5bf28795fa41.jpg)
![Screenshot_20190830-123212](https://user-images.githubusercontent.com/55841755/65698001-23a39380-e07c-11e9-976a-c277cd4b508f.jpg)
![IMG_-gwwodu](https://user-images.githubusercontent.com/55841755/65698073-433abc00-e07c-11e9-90ef-12253c9d1c19.jpg)

**Comment by claireyyl** [comment]
Unblock my Skype/WhatsApp/Telegram, Osman Ungur. You're like a coward just used me and escaped. Where's your compensation, huh?Anyway, I will go to your place next Thursday (Oct/10)or Next Friday (Oct 11th) and stay for 6-7 days because this one part of our fucking deal.
 Pay back the oral sex in Frankfurt and cyber masturbation*2 Osman Ungur as you promised before. Fuck.
https://youtu.be/oBt5AjKpV98   
https://youtu.be/aF8VYZdjKlU

![IMG_4vv2na](https://user-images.githubusercontent.com/56092791/66077819-0af61a80-e561-11e9-91c0-d5bc34a4fc46.jpg)
![P_20190628_195859_vHDR_Auto](https://user-images.githubusercontent.com/56092791/66077832-12b5bf00-e561-11e9-808e-4c92628ec2ff.jpg)
![IMG_-gwwodu](https://user-images.githubusercontent.com/56092791/66077846-1ea18100-e561-11e9-9723-958be9ab2613.jpg)
![IMG_-7nomtc](https://user-images.githubusercontent.com/56092791/66077869-2b25d980-e561-11e9-888a-7be99556b1ce.jpg)
![IMG_fzs812](https://user-images.githubusercontent.com/56092791/66077881-3416ab00-e561-11e9-9a11-fd5b1c81c2ae.jpg)
![IMG_-b9mpd7](https://user-images.githubusercontent.com/56092791/66077895-3e38a980-e561-11e9-98dd-be4661fec1b0.jpg)
![IMG_yoqo8p](https://user-images.githubusercontent.com/56092791/66077911-45f84e00-e561-11e9-800a-607ee177c1b4.jpg)
![IMG_-ubzpbu](https://user-images.githubusercontent.com/56092791/66077959-5c060e80-e561-11e9-8208-040b9036f591.jpg)
![Screenshot_20190821-001219](https://user-images.githubusercontent.com/56092791/66077993-6a542a80-e561-11e9-807e-a2a079a912c6.jpg)
![Screenshot_20190818-003716](https://user-images.githubusercontent.com/56092791/66078010-72ac6580-e561-11e9-9c69-fea4228d9829.jpg)
![Screenshot_20190827-112539](https://user-images.githubusercontent.com/56092791/66078028-7cce6400-e561-11e9-8083-aace54b1f517.jpg)
